### PR TITLE
correct to OVN, not OVS

### PR DESCRIPTION
**Pull request by robinbraemer**

### CODE REVIEW

**Comment by numansiddique** [comment]
@robinbraemer Thanks for the PR. Can you please provide your Signed-off-by tag in the commit message ?
Please see "Tags" section in this -  https://docs.ovn.org/en/latest/internals/contributing/submitting-patches.html

**Comment by robinbraemer** [comment]
Done @numansiddique

**Comment by numansiddique** [comment]
This PR shows that it has 3 commits, which is odd.
Neverthless, I submitted the patch to the OVS mailing list - https://patchwork.ozlabs.org/project/ovn/patch/20201012143344.1771074-1-numans@ovn.org/

The patch LGTM. I'll apply in some time.

Thanks.

**Comment by numansiddique** [comment]
Applied the patch manually - 692e67fb1cd4be0a4bb5e41848f70d44fc72f78f to master.

Thanks. Closing the PR.

**Pull request closed without merging**
