### PR TITLE
add support for building debian packages again

### PR DESCRIPTION
**Pull request by girishmg**
Signed-off-by: Girish Moodalbail <gmoodalbail@nvidia.com>

### CODE REVIEW

**Comment by girishmg** [comment]
@numansiddique @dceara PTAL

Steps to build the debian packages:
```
1. Clone and checkout OVS master branch (say, /root/fix_deb/ovs)
2. Run ./boot.sh && ./configure && make
3. Clone the OVN branch (say, /root/fix_deb/ovn)
4. Install the required package build-dependency (captured in the debian/control file)
   apt-get install graphviz autoconf automake debhelper dh-autoreconf \
   libssl-dev libtool python3-all python3-sphinx python3-twisted libunbound-dev
   libunwind-dev dh-python
5. Now build debain packages from the root of the repo using
   DEB_BUILD_OPTIONS='parallel=8 nocheck' fakeroot debian/rules -e OVSDIR=/root/fix_deb/ovs  binary
6. In the /root/fix_deb folder you will see all the OVN Debian packages.
```

**Comment by numansiddique** [comment]
@girishmg Ack. Thanks for the patch. 

I'll try out the PR.

I think the instructions provided by you can be actually part of the commit message and/or part of the documentation some where.

**Comment by numansiddique** [comment]
@girishmg When I ran -

$sudo DEB_BUILD_OPTIONS='parallel=8 nocheck' fakeroot debian/rules -e OVSDIR=/home/vagrant/ovs/ovs  binary

I get this message - dh binary --with autoreconf,python3 --parallel

**Comment by girishmg** [comment]
@numansiddique I will reach out to you on IRC to debug this.

**Comment by numansiddique** [comment]
Hi @girishmg 

I missed your irc messages.

I tried running again and I see the below error now

root@vagrant:/home/vagrant/ovs/ovn# DEB_BUILD_OPTIONS='parallel=8 nocheck' fakeroot debian/rules -e OVSDIR=/home/vagrant/ovs/ovs
dh_autoreconf --as-needed
dh_autoreconf: warning: Only runs once, see dh-autoreconf(7)

I'm not sure what is going on.

**Comment by numansiddique** [comment]
Thanks Girish for helping me in testing this PR.

I applied this PR manually to master branch.

Can you please submit another PR/patch to add a NEWS item about it ?

Thanks
Numan

**Pull request closed without merging**
