### PR TITLE
debian/changelog: Fix data format

### PR DESCRIPTION
**Pull request by ateleshev**
This PR contains a fix for the issue: https://github.com/ovn-org/ovn/issues/54

Signed-off-by: Artem Teleshev <artem.teleshev@gmail.com>

### CODE REVIEW

**Comment by numansiddique** [comment]
Could you please rebase ?

**Comment by ateleshev** [comment]
@numansiddique done

**Comment by numansiddique** [comment]
@ateleshev Thanks.
I submitted this PR as a patch to the ovs ML for review - https://patchwork.ozlabs.org/project/ovn/patch/20200917125018.994006-1-numans@ovn.org/

Thanks
Numan

**Comment by numansiddique** [comment]
Thanks. I applied this patch to master - https://github.com/ovn-org/ovn/commit/56a66c9d76d3d0b021580f7e4e52b693b6f24c6e
and branch-20.09. Let me know if this needs to be backported to branch-20.06/branch-20.03.

Thanks
Numan

**Pull request closed without merging**
