### PR TITLE
Fix typo in README

### PR DESCRIPTION
**Pull request by fsb4000**
Signed-off-by: Kacper Kamiński <lampo100@gmail.com>

Signed-off-by: Igor Zhukov <ivzhukov@sbercloud.ru>

> Thanks for the patch. Can you please update the commit message with your "Signed-off-by" tag ?

Hi @numansiddique ! I hope I did it right :)
https://github.com/ovn-org/ovn/commit/d093905ba9a8cd0a25b058f00831aca3f3ea51be has 2 "Signed-off-by", if my "Signed-off-by" is not needed I can remove it.

### CODE REVIEW

**Comment by numansiddique** [comment]
@fsb4000 Looks like your signed off is not required since @perkam is the author.

I can take care of that.

Thanks

**Comment by fsb4000** [comment]
Great!

**Comment by igsilya** [comment]
@numansiddique Kacper didn't provide their Signed-off on the patch, so we should not add one, because there might be reasons for them to not do so.  And authors must sign off, patch should not be accepted without a it.
If they are not responding, just disregarding their patch after a reasonable amount of time seems to be a best solution.  You may add them as Suggested-by or Reported-by, but adding any tags without asking may still be inappropriate in some situations.

@fsb4000 regarding your other patch, committer adds their sign-off on the patch before pushing the change, since they are also responsible for changes they are committing.

**Comment by fsb4000** [comment]
@igsilya Ok. Sorry, I want to help.

Hi @perkam ! Could you `git commit --amend` your initial PR and add the needed "Signed-off-by" ?

**Comment by numansiddique** [comment]
@igsilya Thanks for pointing this out.

**Comment by perkam** [comment]
Hi @igsilya @fsb4000 @numansiddique . Sorry about the delay but I got distracted by life :)  Thanks for pointing out all the required metadata - I promise to update my commit with it tomorrow at the latest.
Cheers.

**Comment by fsb4000** [comment]
https://github.com/ovn-org/ovn/pull/138 looks good to me, so I'm closing my PR.

**Pull request closed without merging**
