### PR TITLE
fix ovn-ic blacklist not work on ipv6

### PR DESCRIPTION
**Pull request by changluyi**

### CODE REVIEW

**Comment by rbartzen** [comment]
Hi @changluyi , I opened a bug in LP about this problem. 
https://bugs.launchpad.net/ubuntu/+source/ovn/+bug/2046804

Have you written tests in the OVN testsuite to validate regressions here?

**Comment by tiagonux** [comment]
Hey, we tested this patch and it works fine. Do you know when it will be added to upstream?

**Comment by dceara** [comment]
> Hey, we tested this patch and it works fine. Do you know when it will be added to upstream?

Unfortunately we cannot apply this patch until the author signs off (Developer's Certificate of Origin,), please see [my comment above](https://github.com/ovn-org/ovn/pull/196#issuecomment-1860544390).  The documentation section for submitting patches is available here:

https://docs.ovn.org/en/latest/internals/contributing/submitting-patches.html#tags

It would also be nice if this change had a unit test to make sure this doesn't break in the future.

Thanks,
Dumitru

**Comment by igsilya** [comment]
@rbartzen @dceara unfortunately the only person who can provide a Signed-off-by tag is @changluyi .  So, if the author doesn't respond the only option would be to write a new patch and send it out from your name.  The code in this PR cannot be used as it is copyrighted by default (not a legal advice :D ).  If you do not trust yourself to not plagiarize the code in this PR as you already looked at it, describe the issue to someone else and ask them to write a fix without looking at this PR. :)

**Comment by dceara** [comment]
Closing this in favor of https://github.com/ovn-org/ovn/commit/78750699ab195a1b2c48fbab8546ed0651b05de4

**Pull request closed without merging**
