### PR TITLE
No need snat if packet has been matched ct_dnat

### PR DESCRIPTION
**Pull request by shylou**
#116 No need process the snat lflows in lr_out_snat if the
reply packet has been matched ct_dnat.

### CODE REVIEW

**Comment by shylou** [comment]
I don't know why it is failed in `linux gcc test -ljemalloc `:
`1327: ACL with Port Group conjunction flow efficiency -- ovn-northd -- dp-groups=yes -- parallelization=yes FAILED (ovn.at:28744)`
 But it is sucess in  `linux gcc test`:
`1327: ACL with Port Group conjunction flow efficiency -- ovn-northd -- dp-groups=yes -- parallelization=yes ok`

**Comment by dceara** [comment]
> I don't know why it is failed in `linux gcc test -ljemalloc `: `1327: ACL with Port Group conjunction flow efficiency -- ovn-northd -- dp-groups=yes -- parallelization=yes FAILED (ovn.at:28744)` But it is success in `linux gcc test`: `1327: ACL with Port Group conjunction flow efficiency -- ovn-northd -- dp-groups=yes -- parallelization=yes ok`

This is a known test flake, there's a patch to fix this up for review:
https://patchwork.ozlabs.org/project/ovn/patch/20220401101640.1139426-1-xsimonar@redhat.com/

**Comment by shylou** [comment]
test this please

**Comment by dceara** [comment]
@shylou is this PR still relevnt/needed?

**Comment by shylou** [comment]
> @shylou is this PR still relevant/needed?

Sorry ,  no need this PR now, I will closed it quickly.

**Comment by booxter** [comment]
@shylou could you please clarify why you think this patch is not worth pursuing? Wouldn't it allow to specify a single nat rule for all subnets, while keeping FIP traffic intact?

**Comment by shylou** [comment]
@booxter Yeah, I have committed a patch [1] to deal with this issue for stateful FIP, but it needs to be considered for stateless FIP.

[1] https://github.com/ovn-org/ovn/commit/2d03e9ffb47c397036f7fa5dc13118611382af2d

**Comment by shylou** [comment]
It seems that with this patch[1], stateless FIP could work well.

[1]https://github.com/ovn-org/ovn/commit/c0224a14ffaa4874a7a02500e517adaecd9c5034

**Pull request closed without merging**
