### PR TITLE
WIP: add indent target to Makefile.am

### PR DESCRIPTION
**Pull request by fsb4000**
I'm trying to add a format target to CI so a PR would fail if a patch would not be formatted correctly.

I didn't integrate the target to CI because I have problems 😿 

I looked at: https://github.com/ovn-org/ovn/blob/main/Documentation/internals/contributing/coding-style.rst

But I think I did something wrong because so many changing lines 😿 

How do you check the coding style?

I'll try to find indent options that make less changes.

Also 
```C
/* *INDENT-OFF* */
/* *INDENT-ON* */
```
can be used to disable indent for some lines...

### CODE REVIEW

**Comment by almusil** [comment]
I am afraid that this is too big change with very small added value. Normally the check is done by the 0-day bot per patch on mailing list, maybe we could utilize it for CI as well.  @dceara WDYT?

**Comment by fsb4000** [comment]
>I am afraid that this is too big change with very small added value. 

Yes, no worry.
I didn't want to push 12 000 lines patch :)
So am I correct that we don't have auto formatter?

**Comment by almusil** [comment]
> > I am afraid that this is too big change with very small added value.
> 
> Yes, no worry. I didn't want to push 12 000 lines patch :) So am I correct that we don't have an auto formatter?

There is the 0-day bot,it replies to patches on mailing list if there is something wrong with formatting, applying the patch etc. But it most likely does not implement the full set of rules that described in the coding-style guide.

I agree that having something automated in CI would also be beneficial. Would you mind writing an email to `ovs-discuss@openvswitch.org` to bring up discussion what we can do about that?

**Comment by dceara** [comment]
@fsb4000 patches get sent to the dev mailing list and they also end up on [patchwork](https://patchwork.ozlabs.org/project/ovn/list/).  Then the 0day robot ([ovsrobot](https://github.com/ovsrobot/)) applies them and runs [checkpatch](https://github.com/ovn-org/ovn/blob/main/utilities/checkpatch.py) from the repo itself on the patch:
https://github.com/ovsrobot/pw-ci/blob/master/3rd-party/openvswitch/config.xml#L255

This is the usual workflow.  That's why people are encouraged to post patches instead of opening PRs.

**Pull request closed without merging**
