### PR TITLE
Remove unused OVS code from tree

### PR DESCRIPTION
**Pull request by dave-tucker**
Following the guidance in `TODO_split.rst`
```
* There are likely many unused files throughout the source tree
  since they pertain to OVS rather than OVN. These can also be removed from the
  repo.
```
I diff'd the OVS/OVN trees and identified that the XenServer, IPSEC, Third-Party and AppVeyor files could be safely removed. In addition there was a lot of OVS-only packaging in the `debian` folder but this is taken care of in #36.

I would recommend removing these as it's less code to maintain and to avoid someone mistakenly editing these files and expecting for changes to propagate in to OVN.

### CODE REVIEW

**Comment by blp** [comment]
You can also remove these files from Documentation/ref: ovsdb.5.rst  ovsdb.7.rst  ovsdb-server.7.rst. index.rst in that directory will need an update.

**Comment by dave-tucker** [comment]
Thanks @blp. I've pushed a commit which does that.

**Comment by dave-tucker** [comment]
Oh, and the Third-Party directory too. Compiles on my machine with gcc. Unsure why CI is getting upset but will continue to debug if this fails.

**Comment by numansiddique** [comment]
@dave-tucker Thanks for the PR and apologies for the late response.

I submitted these patches to the ML - https://patchwork.ozlabs.org/project/openvswitch/list/?series=175577 and applied these patches to master.

Closing the PR.

**Pull request closed without merging**
