### PR TITLE
northd: add ddlog implementation for empty_lb controller_event flows

### PR DESCRIPTION
**Pull request by LorenzoBianconi**
Port northd controller_event support from northd c implementation

### CODE REVIEW

**Comment by ryzhyk** [comment]
I don't have the permission to review or merge PRs in this repo, but these changes look good to me. 

Test `200: ovn -- IGMP snoop/querier/relay` is still failing for me though.

**Comment by numansiddique** [comment]
> I don't have the permission to review or merge PRs in this repo, but these changes look good to me.
> 
> Test `200: ovn -- IGMP snoop/querier/relay` is still failing for me though.

Can you please check with Ben or Justin. They can add you to the project.

Thanks
Numan

**Comment by numansiddique** [comment]
@LorenzoBianconi  - Can you please add your Signed-off-by tag in the commit message ?

**Comment by LorenzoBianconi** [comment]
> @LorenzoBianconi - Can you please add your Signed-off-by tag in the commit message ?

@numansiddique: done

**Comment by dceara** [comment]
> I don't have the permission to review or merge PRs in this repo, but these changes look good to me.
> 
> Test `200: ovn -- IGMP snoop/querier/relay` is still failing for me though.

@ryzhyk: Working on it. I'll submit a separate PR once IGMP is ported.

**Pull request merged**
