### PR TITLE
Fix typo in README

### PR DESCRIPTION
**Pull request by perkam**
Hello,
I've noticed a small typo in README :)
Kind regards,
Kacper

### CODE REVIEW

**Comment by numansiddique** [comment]
Hi,

Thanks for the patch.  Can you please update the commit message with your "Signed-off-by" tag ?

Please see the latest commits as an example.  And please take a look at https://github.com/ovn-org/ovn/blob/main/Documentation/internals/contributing/submitting-patches.rst  

Thanks

**Comment by fsb4000** [comment]
Hi @perkam if you need help with submitting the patch I can help.
Folks from Red Hat and ovn organisation  spent some time to explain me how to sent patches 😻

**Comment by perkam** [comment]
@fsb4000 thank you very much for your proposition, that's very kind of you :) Fortunately documentation page linked by @numansiddique was very detailed and helpful.
@numansiddique I've added `Signed-off-by` tag at the end of the commit message. Does it look ok now?
Sorry abouth the delay once again - life got in the way :) It's good to know that you are making sure that even small changes in the project are properly documented and reviewed. Kudos to you.

**Review by fsb4000 — APPROVED** [review]

**Comment by dceara** [comment]
Applied via https://patchwork.ozlabs.org/project/ovn/patch/20240418121054.1317587-1-dceara@redhat.com/

**Pull request closed without merging**
